ARG GOTTY_VERSION=v1.5.0

FROM debian:bullseye-slim AS builder

ARG GOTTY_VERSION

WORKDIR /build

ADD https://github.com/sorenisanerd/gotty/releases/download/${GOTTY_VERSION}/gotty_${GOTTY_VERSION}_linux_arm64.tar.gz gotty-aarch64.tar.gz
ADD https://github.com/sorenisanerd/gotty/releases/download/${GOTTY_VERSION}/gotty_${GOTTY_VERSION}_linux_amd64.tar.gz gotty-x86_64.tar.gz

RUN tar -xzvf "gotty-$(uname -m).tar.gz"
RUN apt-get update
RUN apt-get install git -y
#RUN git clone --depth 1 https://github.com/Torantulino/Auto-GPT.git

##############################

FROM python:3.11-slim

COPY --chmod=+x --from=builder /build/gotty /bin/gotty

WORKDIR /app

COPY --from=builder /build/Auto-GPT/ /app/

RUN pip install --no-cache-dir -r requirements.txt && \
    mkdir /logs


ENV OPENAI_API_KEY=${OPENAI_API_KEY} \
    ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY} \
    SMART_LLM_MODEL=${SMART_LLM_MODEL:-gpt-4} \
    FAST_LLM_MODEL=${FAST_LLM_MODEL:-gpt-3.5-turbo} \
    GOOGLE_API_KEY=${GOOGLE_API_KEY} \
    CUSTOM_SEARCH_ENGINE_ID=${CUSTOM_SEARCH_ENGINE_ID} \
    PINECONE_API_KEY=${PINECONE_API_KEY} \
    PINECONE_ENV=${PINECONE_ENV} \
    USE_AZURE=${USE_AZURE:-False} \
    OPENAI_API_BASE=${OPENAI_API_BASE} \
    OPENAI_API_VERSION=${OPENAI_API_VERSION} \
    OPENAI_DEPLOYMENT_ID=${OPENAI_DEPLOYMENT_ID}

EXPOSE 8080

CMD ["gotty", "--port", "8080", "--permit-write", "--title-format", "AutoGPT Terminal", "bash", "-c", "python main.py  --gpt3only"]
